services:
  hunyuan3d:
    image: rupintalwar/hunyuan3d:latest
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["bash", "-c", "python3 gradio_app.py --disable_tex --low_vram_mode --enable_flashvdm"]
    volumes:
      - ./models:/root/.cache/huggingface/hub
      - ./.u2net:/root/.u2net